import type { Metadata } from 'next';
import { Noto_Sans, Space_Grotesk } from 'next/font/google';
import Header from '@/components/Header';
import Footer from '@/components/Footer';
import './globals.css';

export const noto_sans = Noto_Sans({ subsets: ['cyrillic'], display: 'swap' });

export const space_grotesk = Space_Grotesk({
  subsets: ['latin'],
  variable: '--font-space-grotesk',
  display: 'swap',
});
export const metadata: Metadata = {
  title: 'Project02',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${noto_sans.className} ${space_grotesk.variable}`}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
